### ISSUE TITLE
能否增加标注的显示,就像其他的读书软件一样

### ISSUE THREAD

**Issue by Danielypzhang** [WingDr/siyuan-plugin-sidebar-memo#1]
能否增加标注的显示,像其他读书软件一样,可以显示标注和备注类似微信读书的笔记和想法

**Comment by WingDr** [comment]
没懂你的需求？就算是现在备注，原文也是限定长度然后多的会省略掉。这个插件开发的初衷就是在侧边显示本来不方便显示的备注，标注的话既然都在原文里为啥还要单独列出来在侧边？能不能举个例子？（另外读书笔记这种还是建议用块引，备注更适合小规模零散的附加文字，不值得新建文档甚至不值得用脚注的那种）

**Comment by Danielypzhang** [comment]
比如阅读文章，只是划线句子，如果内容比较多，在侧面像大纲一样显示，点击可以跳转到原文。读书软件不是都是这样显示的么。用块引要一个一个复制，不是很方便。

**Comment by WingDr** [comment]
我知道了，你的需求和这个插件的功能并不相符，可以去看看[“备注增强”插件](https://github.com/zxhd863943427/siyuan-plugin-memo)和[暗色+主题](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus)里的评论功能是否复合你的需求
