### ISSUE TITLE
建议将备注改成紧凑模式

### ISSUE THREAD

**Issue by jtgtifh** [WingDr/siyuan-plugin-sidebar-memo#11]
现在的备注是显示在对应块的旁边，如果一篇文章很长，备注很多，不够直观，没法一目了然。
建议备注按顺序排列即可，但不要显示在对应块旁边，紧凑排列。
然后点击备注时，可以跳转到文档中对应的块；点击文档中有备注的块时，备注栏跳转到对应的备注。

**Comment by WingDr** [comment]
emmm这个需求更建议用反链吧，备注感觉不是用来做这个的，就是一个很轻量化的东西
