### ISSUE TITLE
支持直接点击了备注就可以编辑，取消，删除

### ISSUE THREAD

**Issue by BonjourL** [WingDr/siyuan-plugin-sidebar-memo#2]
支持直接点击了备注就可以编辑，取消，删除

**Comment by WingDr** [comment]
这个太麻烦了，一方面得更新块，另一方面还要自己做编辑的输入框之类的。思源本身的备注功能目前还不成熟，不太值得这么做

最好的选择是有另一个插件用块引的方法做备注，可以[到社区提下想法](https://github.com/siyuan-community/ideas/issues)，或者敦促D大完善思源的备注功能（虽然我觉得现在的备注功能有点鸡肋了
