### ISSUE TITLE
里面内容支持换行显示

### ISSUE THREAD

**Issue by BonjourL** [WingDr/siyuan-plugin-sidebar-memo#3]
里面内容支持换行显示和一些的基本格式

**Comment by WingDr** [comment]
备注本身不支持换行显示和编辑，建议给[思源本体](https://github.com/siyuan-note/siyuan/issues?q=is%3Aopen+is%3Aissue)的备注功能提建议

**Comment by TCOTC** [comment]
思源的备注已 [支持换行](https://github.com/siyuan-note/siyuan/issues/9664) ，请考虑重新打开 issue

![image](https://github.com/WingDr/siyuan-plugin-sidebar-memo/assets/78434827/b1a7e071-7c7d-4bde-b49e-17082874996b)

![image](https://github.com/WingDr/siyuan-plugin-sidebar-memo/assets/78434827/e40cb936-eb27-4bff-9b7a-8e40aeb3e6c0)
