### ISSUE TITLE
侧边备注位置跑偏，聚集到一起

### ISSUE THREAD

**Issue by jiangzhujun** [WingDr/siyuan-plugin-sidebar-memo#4]
作者您好，感谢您写出了这么实用的插件，对我非常有用！
今天我在编辑昨日写的笔记前，从集市下载了“集成编辑环境”插件，然后我发现本笔记的部分侧边备注位置跑偏了，不在原本备注的侧边，而是聚集到了一起，具体情况见下图。之后我把“集成编辑环境”插件关闭甚至删除后都没有恢复，且又将思源重启、恢复昨日的数据历史也无用。
我不确定在下载该插件前是否是这种错位的情况，昨日编辑的时候也没注意到这点。在其他笔记里也有部分侧边备注发生了此种情况。
我今日还执行过的操作包括移动大纲位置。使用的是原生皮肤，思源版本为2.10.10，插件有“日历热力图”、“顶栏日历”、“编辑度宽度”、“配色方案”、“快捷键”、“侧边备注”、“目录插件”、“切换主题”且都已更新。
![image](https://github.com/WingDr/siyuan-plugin-sidebar-memo/assets/52827653/c63a4eb3-259f-4cfa-96bd-0b209abf2542)

**Comment by WingDr** [comment]
诶，可以整个截一下图吗？就是备注挤在一起时整个编辑区的全貌。如果笔记内容比较隐私的话能不能单开一个文档测试下什么情况会挤在一起？主要是我这没办法复现（开启“集成编辑环境”和这个插件），可能是中间某个操作让位置偏移了

**Comment by jiangzhujun** [comment]
好像复现出来了，可能是在文本折叠之后（我这里是列表项，有序和无序都有）在反应一会之后会在上方的某个位置挤在一起，把折叠的段落展开后，侧边备注需要反应挺久来回滚动才能回到原来的位置。这样来说这个可能不算bug。

**Comment by WingDr** [comment]
怎么说呢，说是bug也确实是，主要是开发的时候没考虑到折叠的问题。（思源里面折叠只是不显示，内部还是在渲染的，所以会识别到但是定位会不对）

issue我先关了，目前最好不要折叠着用，等我有空了看下怎么整
