### ISSUE TITLE
能否支持设置默认打开

### ISSUE THREAD

**Issue by LJpLJ** [WingDr/siyuan-plugin-sidebar-memo#5]

**Comment by WingDr** [comment]
没懂啥意思，现在打开插件应该就启用了啊。建议检查一下思源软件的宽度，宽度过小的话不会显示侧栏的（因为就算显示了正文乱成一团也没用）

**Comment by Deanwct** [comment]
> 没懂啥意思，现在打开插件应该就启用了啊。建议检查一下思源软件的宽度，宽度过小的话不会显示侧栏的（因为就算显示了正文乱成一团也没用）

可不可以提供一个配置项出来，可以配置，每次打开笔记，是否也同时打开备注

**Comment by Deanwct** [comment]
更新了0.2.3版本
最新问题: 选项是打开状态，但是备注没有渲染出来
<img width="260" alt="image" src="https://github.com/WingDr/siyuan-plugin-sidebar-memo/assets/18712084/c9ae67be-8291-4920-9467-90dd24e42201">
